name: Tests

on:
  push:
    branches:
      - 1.*
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4, 8.0, 8.1, '8.2']
        laravel: ['8.*', '9.*', '11.*']
        exclude:
          - php: 7.3
            laravel: 9.*
          - php: 7.4
            laravel: 9.*
          - laravel: 11.*
            php: 7.3
          - laravel: 11.*
            php: 7.4
          - laravel: 11.*
            php: 8.0
          - laravel: 11.*
            php: 8.1

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@master

      - name: Select PHP version
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo_sqlite, fileinfo, gd
          coverage: none

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Composer dependencies
        run: composer require "illuminate/support:${{ matrix.laravel }}"

      - name: Show laravel version
        run: composer show laravel/framework

      - name: Install Dependencies
        run: npm install

      - name: Compile Assets
        run: npm run prod

      - name: Run tests
        run: ./vendor/bin/phpunit
